# Site
title:              Ozan Kiratli
bio:                '<i>Evolutionary Ecologist, Lord of the Flies, Computer Nerd, Privacy Activist, Poet, Bass Guitarist, Dad of a Maine Coon</i>'
description:        "Evolutionary ecologist. PhD candidate at the University of Pennsylvania"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
profilepic:         'assets/img/evolozzypp.jpg'
ppmainpage:         'assets/img/evolozzy200.jpg'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://evolozzy.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   none

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              ozankiratli@protonmail.com
twitter:            evolozzy
#facebook:           username
github-url:         evolozzy
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          ozankiratli
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            foto-evolozzy
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com


webrick:
  headers:
    - X-Content-Type-Options: "nosniff"
    - X-XSS-Protection: "1; mode=block"
      #- X-Robots-Tag: "none"
      #- X-Download-Options: "noopen"
      #- X-Permitted-Cross-Domain-Policies: "none"
    - Referrer-Policy: "no-referrer"
    - Strict-Transport-Security: max-age=31536000; includeSubDomains
    - X-Frame-Options: "SAMEORIGIN"
    - Header set X-Content-Type-Options: "nosniff"
    - Feature-Policy: "geolocation 'none';midi 'none';notifications 'none';push 'none';sync-xhr 'none';microphone 'none';camera 'none';magnetometer 'none';gyroscope 'none';speaker 'self';vibrate 'none';fullscreen 'self';payment 'none'"



# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, *.swp]
